language: node_js
node_js:
  - "6"
  - "5"
branches:
  only:
    - master
    - test
env :
    - BROWSSER=chromium_browser
addons:
  firefox: 'latest'
cache:
  directories:
    - node_modules
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script: npm run test
after_success:
  - npm run coverage
