language: node_js
node_js:
  - "6"
  - "5"
branches:
  only:
    - master
env :
    - BROWSSER=chromium_browser
addons:
  firefox: 'latest'
  sauce_connect:
      username: "yeyu456"
      access_key: "711c3db6-9858-4418-aa05-2e74d9d83601"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g gulp
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script: gulp test
after_success:
  - gulp coverage