language: node_js
node_js:
  - "6"
  - "5"
branches:
  only:
    - master
env :
    - BROWSSER=chromium_browser
before_script:
  - npm install -g gulp
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script: gulp test