language: node_js
node_js:
  - "6"
  - "5"
branches:
  only:
    - master
addons:
  firefox: 'latest'
cache:
  directories:
    - node_modules
before_script:
  - npm install -g gulp
script: gulp test
after_success:
  - gulp coverage